In [1]:
import torch
import numpy as np

## tensor

In [2]:
x = torch.tensor([[1, 2]])
x.shape

torch.Size([1, 2])

In [3]:
y = torch.tensor([[1], [2]])
y.shape

torch.Size([2, 1])

In [4]:
x.dtype

torch.int64

## Casting

In [5]:
x = torch.tensor([False, 1, 2.0])
x

tensor([0., 1., 2.])

In [6]:
torch.tensor([False, 1])

tensor([0, 1])

## Zeros and Ones

In [7]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Range

In [9]:
torch.arange(25)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

## Random

In [10]:
torch.randint(low=0, high=10, size=(3, 4))

tensor([[3, 0, 1, 2],
        [6, 2, 8, 4],
        [4, 6, 9, 5]])

In [11]:
torch.rand(3, 4)

tensor([[0.8462, 0.4786, 0.4146, 0.3437],
        [0.5397, 0.8892, 0.2073, 0.6152],
        [0.6797, 0.1365, 0.8982, 0.9529]])

In [12]:
torch.randn((3, 4)) # Normal (Gaussian) distribution

tensor([[ 0.3080,  1.3894, -0.9754,  0.2174],
        [-0.7478, -3.1934, -2.2880,  1.3396],
        [-1.0461,  1.1394,  1.5021, -1.0651]])

## From NumPy

In [13]:
x = np.array([[10, 20, 30], [2, 3, 4]])
y = torch.tensor(x)
type(x), type(y)

(numpy.ndarray, torch.Tensor)