In [1]:
import torch

### Multiplication

In [2]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
x * 10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

### Addition

In [3]:
y = x.add(10)
y

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

### Reshape

Using `view` method.

In [4]:
y = torch.tensor([2, 3, 1, 0])
y.shape

torch.Size([4])

In [5]:
y = y.view(4, 1)
y.shape

torch.Size([4, 1])

Using `squeeze` method.  
This is only possible when the axis we are aiming to terminate **has only one item in that dimension**

In [6]:
x = torch.randn(10, 1, 10)
z1 = torch.squeeze(x, dim=1)
z1.shape

torch.Size([10, 10])

In [7]:
z2 = x.squeeze(dim=1)
z2.shape

torch.Size([10, 10])

In [8]:
torch.all(z1 == z2)

tensor(True)

In [9]:
x = torch.randn(10, 10)
x.shape

torch.Size([10, 10])

In [10]:
z1 = x.unsqueeze(dim=0)
z1.shape

torch.Size([1, 10, 10])

`unsqueeze` equivalent: **Adding [none] indexing**

In [11]:
x = torch.randn(10, 10)
z2, z3, z4 = x[None], x[:, None], x[:, :, None]
z2.shape, z3.shape, z4.shape

(torch.Size([1, 10, 10]), torch.Size([10, 1, 10]), torch.Size([10, 10, 1]))

### Matrix multiplication

In [12]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
torch.matmul(x, y)

tensor([[11],
        [35]])

In [13]:
x @ y

tensor([[11],
        [35]])

### Concatenate

In [14]:
x = torch.randn(10, 10, 10)
z = torch.cat([x, x], axis=0)
x.shape, z.shape

(torch.Size([10, 10, 10]), torch.Size([20, 10, 10]))

Essentially, if we consider x to be a matrix with ten rows and ten columns, with each entry corresponding to a ten-dimensional array, `cat` with **axis=0** implies combining the rows of two matrices together.

In [15]:
z = torch.cat([x, x], axis=1)
x.shape, z.shape

(torch.Size([10, 10, 10]), torch.Size([10, 20, 10]))

With **axis=1**, on the other hand, it's as if we treat x as ten 10x10 matrices and add to those ten 10x10 matrices.

### Max

In [16]:
x = torch.arange(25).reshape(5, 5)
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [17]:
x.max()

tensor(24)

In [18]:
x.max(dim=0)

torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))

According to the aforementioned result, we can get the maximum of each column by calling `.values` and the **argmax** of each column by using `.indices`.

In [19]:
max_values, argmax = x.max(dim=1)
max_values, argmax

(tensor([ 4,  9, 14, 19, 24]), tensor([4, 4, 4, 4, 4]))

### Permute
Permute the dimensions of a tensor object.

In [20]:
x = torch.randn(10, 20, 30)
z = x.permute(2, 0, 1)
x.shape, z.shape

(torch.Size([10, 20, 30]), torch.Size([30, 10, 20]))

**Difference between `permute` and `view`**: By reshaping dimensions, it sequentially reads data from the upper dimensions to the lower ones. permute on the other hand, preserves ordering.

In [21]:
x = torch.arange(8).reshape(4, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [22]:
x.reshape(2, 4)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [23]:
x.permute(1, 0)

tensor([[0, 2, 4, 6],
        [1, 3, 5, 7]])